### ISSUE TITLE
add describegraph process

### ISSUE THREAD

**Issue by thejerrod** [Gridflare/lndpytools#1]
Never heard of describegraph before, and its important for this process

Suggesting a small addition to cover that piece:

On your node, create the json file used to power the improvecentrality.py script. The describegraph.json file must reside in the same directory as the script.
`$ lncli describegraph > describegraph.json`

**Comment by Gridflare** [comment]
This is a good idea, I will update the documentation accordingly.

**Comment by Gridflare** [comment]
Thanks for the feedback! The README has now been updated
