### ISSUE TITLE
Cannot connect to remote node

### ISSUE THREAD

**Issue by dmp1ce** [Gridflare/lndpytools#13]
I have a `node.conf` configured to find my `tls.cert` and `readonly.macaroon` with the correct server address, but I still cannot connect. I get this error:

```
Traceback (most recent call last):
  File "/home/david/Workspace/lndpytools/nodeinterface.py", line 210, in <module>
    print('Connected to node', ni.getAlias())
  File "/home/david/Workspace/lndpytools/nodeinterface.py", line 190, in getAlias
    return self.GetInfo().alias
  File "/home/david/Workspace/lndpytools/nodeinterface.py", line 45, in rpcCommand
    return stubfunc(lnfunc(*args, **kwargs))
  File "/home/david/.local/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/david/.local/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1649818912.783105054","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1649818912.783104544","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

I have `rpclisten=0.0.0.0:10009` set in the `lnd.conf`. Can you give me a suggestion on how to debug this?

**Comment by dmp1ce** [comment]
I have `tlsextraip=0.0.0.0` set as well. I'm on version `v0.14.2-beta` of LND.

**Comment by Gridflare** [comment]
I'm on LND 0.14.1, so it could be the RPC files.

Is `0.0.0.0` valid in TLS? Usually you want that value set the same as the server IP in the configuration file.

**Comment by Gridflare** [comment]
I have just pushed the new RPC files. Run `git pull` and see if you still have the same issue.

**Comment by dmp1ce** [comment]
I still had the same issue. Let me try to regenerate my `tls.cert`.

**Comment by dmp1ce** [comment]
I set `tlsextradomain` and `tlsextraip` and the connection works now. Thank you!

I regenerated the `tls.cert` by deleting the `tls.cert` and `tls.key` and restarting LND. That's the only way I know how to apply the new settings. There is probably a way without stopping LND.
