### ISSUE TITLE
graph age check should avoid times in the future

### ISSUE THREAD

**Issue by zx9r** [Gridflare/lndpytools#17]
last_update field in graph edges can have a date in the future. That is because channel policy info can be whatever a node sends. It is not checked by lnd since it would be tricky because clocks aren't always in sync

So, this dates in the future should be avoided when checking if the graph is too old (currently more than 6 hours)

I'm sending a pull request to solve this

**Comment by Gridflare** [comment]
Merged, thanks for the contribution!
