### ISSUE TITLE
Feature request: ignore fresh channels

### ISSUE THREAD

**Issue by C-Otto** [Gridflare/lndpytools#3]
When I run `checkchannels` on my node, the recommendations list contains several channels that are just a couple of days old. My own fee adjustment scripts need around 1 month to reach low levels, and I don't expect channels to perform in that time frame. As such, I'd appreciate a grace period in the computation, so that only old and useless channels show up in the `checkchannels` output. Let's say 2016 blocks aka 2 weeks?

**Comment by Gridflare** [comment]
That's a good idea. I think doubling that to 4 months might be even better. 
When listing the channels, should there also be a flag for young channels?

**Comment by C-Otto** [comment]
Yes, that should help avoid confusion ("why isn't it in the recommendation list?"). And it's fair, as "never sent" and "never sent, very new channel" sound very different to me.

**Comment by Gridflare** [comment]
I've just pushed this improvement, let me know how it works for you

**Comment by C-Otto** [comment]
Perfekt, thank you!
