### ISSUE TITLE
Error running improvecentrality.py - TypeError: '<' not supported between instances of 'DegreeView' and 'int'

### ISSUE THREAD

**Issue by hgoodrow** [Gridflare/lndpytools#5]
Running this under Python 3.8.10 on a Windows Subsystem for Linux (WSL)  Ubuntu 20.04 distro.  The node is on my local network and other scripts like nodeinterface.py work fine. 

Command 'python3 ./improvecentrality.py'.
![image](https://user-images.githubusercontent.com/8390696/126258961-084e720c-ebdc-4f1a-b576-e7fe6259f4c5.png)

**Comment by Gridflare** [comment]
It looks like your node was not found in the graph. Please double-check the key in improvecentrality,conf
I will add a error for this.

**Comment by hgoodrow** [comment]
I did not see a step in the improvecentrality.py file to add my nodes public key in the improvecentrality.conf file. After adding it the program completed successfully.

**Comment by Gridflare** [comment]
The script should have said "Please complete the config and rerun" upon first run, is there a way to improve this message?
I have also added a proper explanation if the pubkey was not found in the graph.

**Comment by hgoodrow** [comment]
I would make the message say something more specific like: "The nodes public key was either not found or was invalid.  Please verify that the pub_key setting in the improvecentrality.conf has the correct public key for your node and re-run the program".

**Comment by Gridflare** [comment]
That's similar to the error message I just added. Upon first run, the program cannot check the key for validity before you have a chance to enter it, that's why the initial message has to be so simple.

**Comment by hgoodrow** [comment]
This looks fine: https://github.com/Gridflare/lndpytools/commit/c2520290e8cc64fbd9c9891c3df36a259caefcce
