### ISSUE TITLE
Error While Running

### ISSUE THREAD

**Issue by bensig** [Gridflare/lndpytools#6]
After installing requirements.txt, I ran nodeinterface.py and got the following error. I do not have a node.conf file.

```
$:~/src/lndpytools$ python3 nodeinterface.py
  File "nodeinterface.py", line 160
    while (fwdbatch := getfwdbatch(starttime, offset)):
                    ^
SyntaxError: invalid syntax
$:~/src/lndpytools$ python3 --version
Python 3.7.9
```

**Comment by Gridflare** [comment]
This is a Python version issue. Do you have access to Python 3.8+?
If not, what OS are you running? I can look into adding venv instructions.

**Comment by bensig** [comment]
I'll install venv - but you may want to consider using https://python-poetry.org/ 

I'm running:
```
Debian GNU/Linux 10 \n \l
Linux version 4.19.0-6-amd64 
```

**Comment by bensig** [comment]
I decided to use pyenv instead of venv - I think it is much better than just using venv 

Easily install with `curl https://pyenv.run | bash` or follow this [tutorial](https://realpython.com/intro-to-pyenv/)

Now getting a new error @Gridflare 
```
Fetching graph for further analysis
Checking up to 23 least used public channels for removal centrality impact
Waiting for base centrality computation to finish
An SSL warning may appear, please contact if you know the cause
Traceback (most recent call last):
  File "checkchannels.py", line 150, in <module>
    printcentralitydiffs(mynode, myneighbours)
  File "checkchannels.py", line 111, in printcentralitydiffs
    print(f'Progress: {counter}/{njobs} {counter/njobs:.1%}',
ZeroDivisionError: division by zero
```

**Comment by Gridflare** [comment]
Looks like it didn't find any candidates, I think that could happen if it thinks all your channels are young, I'll have to look into that.

I'm willing to support whatever dependency management solution is the easiest to instruct noobs to use.

**Comment by Gridflare** [comment]
I've just pushed 314fb30 to address the checkchannels issue

**Comment by Gridflare** [comment]
I've commented out the code that requires 3.8+ for now, when it becomes required I'll look into rewriting it with the old-fashioned logic
